replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.765-g91515d
  pullPolicy: Always
  sha: sha256:eeed5371922fe991e7122252e85fa3f801232a55b8ab80f30162abf0b244e5f4
internal_nginx: 'OFF'
