replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.783-g748f35
  pullPolicy: Always
  sha: sha256:4c203ba720e551248b35d31ccbdc0e4f7e158cd7565ba58d46f2f67e8308f1ce
internal_nginx: 'OFF'
