replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.790-g3a81a8
  pullPolicy: Always
  sha: sha256:f549d621e4ec461b34af49d2d70866299a504bf3894e921f27ca57c9ad7cff23
internal_nginx: 'OFF'
