replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.769-gd5c62b
  pullPolicy: Always
  sha: sha256:9f53f62c649fce32056ceecae97e30a18d19529ff177a9ae28998bddb6d605c4
internal_nginx: 'OFF'
