replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.797-g6fce89
  pullPolicy: Always
  sha: sha256:f441a2751cfd7a13ce5472a36a5d397c7f98650af00c05b0156a6f7eb07d89b8
internal_nginx: 'OFF'
