replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.828-ga85a11
  pullPolicy: Always
  sha: sha256:4338ae041702ad35fec770a164316c6e59200befc93b72561bf99bd3a8278e04
internal_nginx: 'OFF'
