replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.846-g23686a
  pullPolicy: Always
  sha: sha256:d82060fca067e0c7f580f932dbeb65e05cc7d3f0bf6fb5fd63cd31e0359e2d13
internal_nginx: 'OFF'
