replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.775-g4d1a8a
  pullPolicy: Always
  sha: sha256:9ba13b5563fd1ed5df4dace3362c8685a1ca0c8ed567b56cc24054a00a9a1e40
internal_nginx: 'OFF'
