replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.821-ged742a
  pullPolicy: Always
  sha: sha256:291d4b957d35f0729bd2fe394cefe26d6c5766431e6b49b620959790fc268923
internal_nginx: 'OFF'
