replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.832-g770403
  pullPolicy: Always
  sha: sha256:79d6b8674cf91f563d5dbe5edc07af1f086d9294f2219fe472f58802c1e05622
internal_nginx: 'OFF'
