replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.781-gc6ace0
  pullPolicy: Always
  sha: sha256:38b3a6684e66b3bd72a7a8db41b3df915fa42b71215849655ca509ec40d24651
internal_nginx: 'OFF'
