replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.791-g3fa2dd
  pullPolicy: Always
  sha: sha256:b57c3ee3fc078a8578eeafaf0c1a9914bdb58413c0fcc744dd9591ae09b998d4
internal_nginx: 'OFF'
