replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.837-g6049e1
  pullPolicy: Always
  sha: sha256:3cd78e3a434486595179be04e912a58133b44614575bf0dece8ab414074f7060
internal_nginx: 'OFF'
