replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.848-gc11f8e
  pullPolicy: Always
  sha: sha256:b134278b29def05f07ed6f2272674d6625d37132bc3386b04ecc028a0802f763
internal_nginx: 'OFF'
