replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.799-ga2ea7b
  pullPolicy: Always
  sha: sha256:8e1357208a52d76dde5850094dfc0232333876a00940c5c17853a22439d7a7b3
internal_nginx: 'OFF'
