replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.767-g9ecbd3
  pullPolicy: Always
  sha: sha256:005d9df127ab48fdac5e621651acb2f7e9cb89f1239e580b90453f1bbfd53dcf
internal_nginx: 'OFF'
