replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.843-g5e534b
  pullPolicy: Always
  sha: sha256:788522a0d02a3a43e60cb3c367211a7c09dfb987a68ab4c44160dcf14d765dc7
internal_nginx: 'OFF'
