replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.850-g4f10b7
  pullPolicy: Always
  sha: sha256:de4f2937aa2477ba4f81c3ec6baf16ac68a74560cd0e7c830972e5c32ecdb9cc
internal_nginx: 'OFF'
