replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.859-gc8d0fe
  pullPolicy: Always
  sha: sha256:533be0bbea122e8afe745dbebd91e327060633d60db5e49efe12f4998484e6f5
internal_nginx: 'OFF'
