replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.804-gd87376
  pullPolicy: Always
  sha: sha256:9679dc3282611580585cd038c51eefa10bcc2b8efa98b2120c54b0c3257e4d71
internal_nginx: 'OFF'
