replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.777-g4b35dd
  pullPolicy: Always
  sha: sha256:d1069f390de8693b8e9911b7129bc2d42fe30e20c3ef38827e053262eddf381f
internal_nginx: 'OFF'
