replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.810-gb23d26
  pullPolicy: Always
  sha: sha256:000789523d7a9171b289868664e6a420ebf6ff2b9edfc9c6803fe6f3e4662527
internal_nginx: 'OFF'
