replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.826-gab845b
  pullPolicy: Always
  sha: sha256:8bada9adc76e4c60d81333809f51036a4a14bf13d8a97345576bb194f57069e3
internal_nginx: 'OFF'
