replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.788-g94537a
  pullPolicy: Always
  sha: sha256:83223a8948bc161750aca9f3a6e38d38f468dd2788996800c3980fd51910e601
internal_nginx: 'OFF'
