replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.852-g14958c
  pullPolicy: Always
  sha: sha256:be1605ae213207a63503693f5acf4f4995f855a6f4e30fd5f20300d6e86117cf
internal_nginx: 'OFF'
