replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.861-gcac014
  pullPolicy: Always
  sha: sha256:c708e7eac729ffa35d148f36cfa1a4852276d60da60fb8017a465f3686a1a2ff
internal_nginx: 'OFF'
