replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.803-ga8386a
  pullPolicy: Always
  sha: sha256:c238ef49f3e809adf312ddeeff37f87b28f97e0d6a5a4863f5c1052366943168
internal_nginx: 'OFF'
