replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.771-g0dddd9
  pullPolicy: Always
  sha: sha256:c278b26dada5d71ca2dee6ed30133b74ade50c2850584233677f560280922a42
internal_nginx: 'OFF'
