replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.813-g902d9f
  pullPolicy: Always
  sha: sha256:71a6e4ee171bfecbf348d1dac19f70ad2540f3d7db990703b1e9d123a36e690f
internal_nginx: 'OFF'
