replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.819-ga45cec
  pullPolicy: Always
  sha: sha256:d562444c67be50d80ffec8a0e4d03e1587742fcdabfa97a889a671a0d745d55f
internal_nginx: 'OFF'
