replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.786-gb0b5d6
  pullPolicy: Always
  sha: sha256:5384baed93c95a55314da7bfa84415d2521e534666d5bc5470b5a28deda496d3
internal_nginx: 'OFF'
