replicaCount: 1
image:
  repository: quay.io/deployhub/ms-ui
  tag: svccat-v11.0.857-g1a7fa7
  pullPolicy: Always
  sha: sha256:1e846b7b1b4c69574c4940b3624b76fe5526e52b4a93bb228daea746c9f18603
internal_nginx: 'OFF'
