replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.806-gc18608
  pullPolicy: Always
  sha: sha256:b82532266e05a62b32f398a474c04c148e962fe741bf545905eb340bd4834120
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
