replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.861-gcac014
  pullPolicy: Always
  sha: sha256:00ae9111bc3d193d4aee304865ba680c934d7fa4ba629ebe00f299aa8b2f3ddf
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
