replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.859-gc8d0fe
  pullPolicy: Always
  sha: sha256:a3b03a05c570af59b8747c5ee6522f8c9d987f3bf36fbb05c03a3b38cb770ff2
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
