replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.799-ga2ea7b
  pullPolicy: Always
  sha: sha256:b94bfdeeae0c394e5684a4b96bf2e7fe5476eb9dde981c921272e3869b23953f
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
