replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.765-g91515d
  pullPolicy: Always
  sha: sha256:e385407faf0cbbd9981da76a917dc855f77cb08c815578eb638f84461c5affc8
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
