replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.863-g157418
  pullPolicy: Always
  sha: sha256:6947235cc83a9319066bdbba9015363e79aff888cebdb843f79bd4cdfbe02ea0
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
