replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.803-ga8386a
  pullPolicy: Always
  sha: sha256:a2db2d62e6cb9ac3588f75cb2daa31f9fb7eb918befc5e4fcc61ad675567e254
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
