replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.783-g748f35
  pullPolicy: Always
  sha: sha256:bc1a15ffe770d2c87b102083b0f4a7856ade3a17fad22db99029e81a808dccf3
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
