replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.848-gc11f8e
  pullPolicy: Always
  sha: sha256:490a8055215a393b7df6409773c91a35a31d9bf5c049e31bbbfc6a7b5476c4d0
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
