replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.797-g6fce89
  pullPolicy: Always
  sha: sha256:c8adcdfe6693236d5435e866eb9f960bc681b826d4b2ebbcced3c5c4c904dab8
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
