replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.786-gb0b5d6
  pullPolicy: Always
  sha: sha256:c2ae3ff24127e5bf065e1a87d768990c09e51cbf93e202f9ef7ea0ab89d34b47
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
