replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.817-g1c3b5c
  pullPolicy: Always
  sha: sha256:af67eae887c15d2990ee665731e30d7f624d9515a646cd18214e6aef3c33728b
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
