replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.801-g619a16
  pullPolicy: Always
  sha: sha256:425a107991bc7758bc07e6f81ddc414eb0f4306eb8c8194298b34e13d941c867
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
