replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.775-g4d1a8a
  pullPolicy: Always
  sha: sha256:181a429102bd7b5806b4c7e113632e3146a865fc8005922ce04c6ca0b861911b
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
