replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.855-gc3b6e0
  pullPolicy: Always
  sha: sha256:807b0c52a04650edca35273e4ca5f39579de814934f5af6e7970eaf5bf4ae4f9
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
