replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.795-g99fb51
  pullPolicy: Always
  sha: sha256:a10df8622a27ef876b3bbbced4e3f5ab83bd06ddfa26fb9a74f43fca61deaca4
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
