replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.815-g717581
  pullPolicy: Always
  sha: sha256:d2d3400664e852d0264fe78e0d3c390d4f0ca0f22c5507ae3b5f34080aa6fe5d
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
