replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.779-gcfce27
  pullPolicy: Always
  sha: sha256:da08a9fdecde1124544a94eff668edea791b923b8424bf720f5f65402a18292d
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
