replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.781-gc6ace0
  pullPolicy: Always
  sha: sha256:b308a7a356b5453802f0d2c4d61aec24153ad6795463053236666fc12f85f594
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
