replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.857-g1a7fa7
  pullPolicy: Always
  sha: sha256:5a3486b5ab5c696a6d5a0591f22800bd3f453b19fb9ad31a84ed4ecee80bc941
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
