replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.788-g94537a
  pullPolicy: Always
  sha: sha256:ef961fe084394679d72850b63dc480d28f12ae46272a3d198aaf5709b17dd254
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
