replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.821-ged742a
  pullPolicy: Always
  sha: sha256:cc12e3b8ac238f671d87e10466c5d2ba3b57a555177b2e4dd742bab0f7797561
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
