replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.830-gd503ea
  pullPolicy: Always
  sha: sha256:92c6bcdce1b9fce28bf4e9fd8cb72e406ec83ec8ea9bd73c12a49b97c31ed0df
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
