replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.793-g093920
  pullPolicy: Always
  sha: sha256:df5c7ff7db1d2c80056a08f569a35262876b26409ff1d82406e16e7f483d0e77
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
