replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.810-gb23d26
  pullPolicy: Always
  sha: sha256:85b304e715e2b66a049313bfda5afab41da472a2d824a4f78337b5d8a988e2be
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
