replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.837-g6049e1
  pullPolicy: Always
  sha: sha256:2daa4d26f58d84cfcbe5be285fde9dd186b2aada955b1e80fc64906784aecbc2
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
