replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.808-g418b5d
  pullPolicy: Always
  sha: sha256:1ee99bb7442f1ecc0793396d141ad881ca3b4edb4c1243fa5b96b47ddaf16cdd
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
