replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.771-g0dddd9
  pullPolicy: Always
  sha: sha256:e8988ed9dc87b9e6a2bbc99112b9dd4cb5fc7b72d5470278a3a0c9371b89ae3a
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
