replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.769-gd5c62b
  pullPolicy: Always
  sha: sha256:6d63048f93443869cda66ca10edce89460da715fb87be27e3dd950586d32cec3
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
