replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.846-g23686a
  pullPolicy: Always
  sha: sha256:12c83287748eae2eff26874271f9b23108a6e8d1d8b3c9e337d443dc59f5bcb9
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
