replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.835-g7dae22
  pullPolicy: Always
  sha: sha256:33b7e4e42b0209c94ca74ab70f016f2c3112021661b8a4833556ae4bfece9620
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
