replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.791-g3fa2dd
  pullPolicy: Always
  sha: sha256:e3532dbe53142e763194270fea16f147894fcc2391a2c019e4e579cbfa858f21
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
