replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.804-gd87376
  pullPolicy: Always
  sha: sha256:1c57c46fe1b35bc5e7e0af7d4f04e6a1dce462640e5058271e82ef63a5863452
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
