replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.813-g902d9f
  pullPolicy: Always
  sha: sha256:70dc726501fe16dbab3fe4aa58252996e40ae76554eb091e085a2d6ea24bc778
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
