replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.828-ga85a11
  pullPolicy: Always
  sha: sha256:cb76ac8c3269c2f602c1d17c4b66127c6944b86628c462d80703e2dac5bf0540
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
