replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.773-gc5a2df
  pullPolicy: Always
  sha: sha256:970fda247c36a2d31cffa234623cbc67cef99b43ec1bafd282cef0f4bd16df50
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
