replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.785-g5678e6
  pullPolicy: Always
  sha: sha256:0f9856e727725d3bd7afbfca86aba820592211242cd0641eaba3269159a9a54c
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
