replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.850-g4f10b7
  pullPolicy: Always
  sha: sha256:f22b72e19fdcdf72cff39244733980c7c9d0642bd02a411b085b42a62316692f
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
