replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.843-g5e534b
  pullPolicy: Always
  sha: sha256:6f918cb4b4d5f922b0a513978d9bba78677a8860b43e3f01b634cf2b534d1cbf
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
