replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.852-g14958c
  pullPolicy: Always
  sha: sha256:760ae913b8b3aaba71fc38f0d4a042e771e34f91c3d250cdca971408dc2b09b0
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
