replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.841-g5f0637
  pullPolicy: Always
  sha: sha256:2494ea74a7d89f70fcc134daea2c55846e8ef43d81a4bc78f05c4369ecf5110c
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
