replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.790-g3a81a8
  pullPolicy: Always
  sha: sha256:83f1bd02a23028b844133dfcddd1e64947c7d36b2f8a738d1ed86175a43e6a71
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
