replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.832-g770403
  pullPolicy: Always
  sha: sha256:8d9b14a53589db64336fdb6b1cfae0ad1664ae2eaf83c3d62e72f2ded4a5ea74
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
