replicaCount: 1
image:
  repository: quay.io/deployhub/ms-nginx
  tag: svccat-v11.0.777-g4b35dd
  pullPolicy: Always
  sha: sha256:7ecfbcc08d7429757ecc7123a872bac337b26a8af01e3bef4ec66548ef085c17
ingress:
  enum:
    alb: 'OFF'
    glb: 'OFF'
    volumemnt: ''
    sslcert: 'ON'
    ssloff: 'OFF'
  type: ssloff
  alb_certificate_arn: null
  alb_subnets: null
