replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.765-g91515d
  pullPolicy: Always
  sha: sha256:3f3ff90d8f23eeaeaa51d562f11753c4349d4d49b4e31bf2cdbf73ed229afb54
internal_nginx: 'OFF'
