replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.775-g4d1a8a
  pullPolicy: Always
  sha: sha256:4c26f05f2215af396a17fdcf21073c31968a266177d64bc77c180197821c8b53
internal_nginx: 'OFF'
