replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.797-g6fce89
  pullPolicy: Always
  sha: sha256:a45a979b9776fed537d23d7e723c9263d21cf2fee5a247f86e6bea35bfa55081
internal_nginx: 'OFF'
