replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.795-g99fb51
  pullPolicy: Always
  sha: sha256:3b7edef63ad1d6a0fb44c634800c02f104b86038febe83c16da0390fe675f102
internal_nginx: 'OFF'
