replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.846-g23686a
  pullPolicy: Always
  sha: sha256:216cbb249c887f5e191a083e70503688572d920db4f89458e302c3b7ba880e3e
internal_nginx: 'OFF'
