replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.804-gd87376
  pullPolicy: Always
  sha: sha256:032bf7136351799bc2cbc3329d9822fd61036366ad5c65a717e688086d1e407d
internal_nginx: 'OFF'
