replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.788-g94537a
  pullPolicy: Always
  sha: sha256:b602536da2d5f79f9d41183c0edc34b9237eb6e513ed93852d4af58af0de17d2
internal_nginx: 'OFF'
