replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.857-g1a7fa7
  pullPolicy: Always
  sha: sha256:493a08dc7a5ed66dc767feb11303b855213a51315d18aa560a7955a2e75ae67a
internal_nginx: 'OFF'
