replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.817-g1c3b5c
  pullPolicy: Always
  sha: sha256:78ae39806efcba1713be3d86e451e5e309439e2d8ab3dc49750b8f25af8a376e
internal_nginx: 'OFF'
