replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.799-ga2ea7b
  pullPolicy: Always
  sha: sha256:086b7b1c58d770bc9d9c2372efb8e43f6d8fcb5b554b4b3b80d4691fbdc96db5
internal_nginx: 'OFF'
