replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.841-g5f0637
  pullPolicy: Always
  sha: sha256:62ec3543343ae346cf218f2af29f654fd3eb737ffcc88baa2339195ab6e5f1ca
internal_nginx: 'OFF'
