replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.843-g5e534b
  pullPolicy: Always
  sha: sha256:12f7b1e2113e09bf0f2e9bbd4bc3d1f076fac16ac69b1e6f0bb78c22866d5cc5
internal_nginx: 'OFF'
