replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.781-gc6ace0
  pullPolicy: Always
  sha: sha256:13f401b8baf91f33378950d19b11d868da58faf7a0632c90596c3b5a259eada8
internal_nginx: 'OFF'
