replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.810-gb23d26
  pullPolicy: Always
  sha: sha256:879c01d88a7186eef1e7d61b996137c35cc6dd3f7ab1253cc0aa792cba8ba2a4
internal_nginx: 'OFF'
