replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.791-g3fa2dd
  pullPolicy: Always
  sha: sha256:90ffea346f1d4d9a0a01e6a25867ce42012335d18b3c0b0bbd06ac0ec2421589
internal_nginx: 'OFF'
