replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.850-g4f10b7
  pullPolicy: Always
  sha: sha256:fe17e2597be1453eefc0bf30394301ce38bc3c1b267c61decd309ce8ffd28630
internal_nginx: 'OFF'
