replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.801-g619a16
  pullPolicy: Always
  sha: sha256:fc52c21a2ba3665969a49aab30504692ad8301672bba4cb6cb0c9eb9bebd28e6
internal_nginx: 'OFF'
