replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.777-g4b35dd
  pullPolicy: Always
  sha: sha256:0346d759ace484f4c226eddf95b08cc9192988dd056b618c7e241c28c5c42433
internal_nginx: 'OFF'
