replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.832-g770403
  pullPolicy: Always
  sha: sha256:07c8bf19a72454fe939bcb513e9e799f7a4819e8f9188e54e3594099d38a8493
internal_nginx: 'OFF'
