replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.830-gd503ea
  pullPolicy: Always
  sha: sha256:eba9e542a51b263bfcfc48563d07753f616e4dbb0c1e76be2a0ff2bda04cf197
internal_nginx: 'OFF'
