replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.815-g717581
  pullPolicy: Always
  sha: sha256:65a93c28eff72256d116d5d3f5bbd7e6f7f8ad48a543c81fc6580416150e0cb9
internal_nginx: 'OFF'
