replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.861-gcac014
  pullPolicy: Always
  sha: sha256:75443754874a0f8d7c6d5ba595503d3629b0078955f58234033fb2344dfce23a
internal_nginx: 'OFF'
