replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.769-gd5c62b
  pullPolicy: Always
  sha: sha256:39215a8906b790483ffc8ecff55ca0c4931afc663b4259ee2b24df6762703d97
internal_nginx: 'OFF'
