replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.786-gb0b5d6
  pullPolicy: Always
  sha: sha256:cb31e66ff4944f8b8a9782e732730525d7aff0eb4a966d18c6e8863ed7fced44
internal_nginx: 'OFF'
