replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.767-g9ecbd3
  pullPolicy: Always
  sha: sha256:0e393b8b0e97242c4c9ac550b83cfe2fb88a7bcb94ea41d26e4be8278e2f7eb4
internal_nginx: 'OFF'
