replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.819-ga45cec
  pullPolicy: Always
  sha: sha256:ecaf83dc2f4ff7097249613b1dbba9fd85511f5a57e7e4e692dcde3609c0ab98
internal_nginx: 'OFF'
