replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.790-g3a81a8
  pullPolicy: Always
  sha: sha256:bc3c7d2b03bcfc2d09ce6400c02f11ae0b1f94ae5fa43cfab0c4de1fc73d054f
internal_nginx: 'OFF'
