replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.848-gc11f8e
  pullPolicy: Always
  sha: sha256:6797c0971672a952fd54074f1a93e639962098a2a8106b5ef3968189d2149f29
internal_nginx: 'OFF'
