replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.808-g418b5d
  pullPolicy: Always
  sha: sha256:33af92bc3d4d51143819f714bb04962e3a57a38d1ed45a76c948e4d2689897a9
internal_nginx: 'OFF'
