replicaCount: 1
image:
  repository: quay.io/deployhub/ms-general
  tag: svccat-v11.0.828-ga85a11
  pullPolicy: Always
  sha: sha256:1522620cb061325f99e387690c5d51a0cc9c8b97185ffc08326f2a1656f6cefe
internal_nginx: 'OFF'
